#!/bin/bash

# NHK
NHK="$HOME/.nhk"
NHKCFG="$HOME/.nhk/xt/cfg"
CORE="2"

# browser
WEBDIR="$NHK/.mtn"
WEBHIST="$WEBDIR/.mtnhist"
WEBD="$WEBDIR/dwn"

# applications
TRM="urxvt" 
TXT="nvim"
MU="$TRM -e ncmpcpp"
WEB="$TRM -cd $WEBD -e w3m"
IM="$TRM -e concord"
IX="$TRM -e aerc"
FM="$TRM -e lf"
KANATA="$HOME/kanata.kbd"

# theming
FONT='Terminus:pixelsize=10:antialias=true'

wideps() { # ignore this 
    case "$1" in
        "gentoo")

	 sudo emerge -av dev-build/make dev-util/cmake x11-libs/cairo x11-libs/libx11 x11-libs/libxft x11-libs/libxinerama dev-vcs/git dev-lang/python x11-libs/pango dev-util/pkgconf dev-libs/gobject-introspection app-misc/lf x11-misc/xsel sys-process/htop app-misc/brightnessctl x11-misc/redshift net-p2p/rtorrent x11-terms/rxvt-unicode x11-misc/rofi app-editors/neovim x11-libs/libwnck x11-apps/yajl media-libs/freetype x11-apps/shotgun x11-apps/xclip media-fonts/terminus-font media-gfx/ueberzug app-multiplexers/tmux net-libs/webkit-gtk x11-misc/gcr x11-apps/xsetroot mail-client/aerc dev-python/userpath dev-python/pipx --oneshot
	 git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
	 cd ~/dmenufm && \
	 make && sudo make install && \
	 cd ~/ && \
	 git clone https://github.com/rvaiya/warpd.git && \ 
	 cd warpd/ && \
	 make && sudo make install && \
	 cd ~/ && \
	 rm -rf warpd/ && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
	 chmod +x emojimenu && \
	 sudo mkdir -p /usr/share/emojimenu && \
	 sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
	 sudo mv emojimenu /usr/local/bin/emojimenu && \
	 git clone https://github.com/darkhz/bluetuith && \
	 cd bluetuith && \ 
	 go build main.go -o bluetuith-bin && \
	 mv bluetuith-bin /usr/bin/bluetuith && \
	 cd ~/ && \ 
	 git clone https://github.com/kspi/dmenu-frecency && \
	 sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
	 cargo install hacksaw && \
	 curl -fsSL https://raw.githubusercontent.com/AlfredoSequeida/hints/main/install.sh | bash 
	 ;;

        "debian")

	 sudo apt install -y build-essential cmake libcairo2-dev libx11-dev libxft-dev libxinerama-dev git python3 libpango-1.0-0 pkg-config libgirepository1.0-dev lf xsel htop brightnessctl redshift rtorrent rxvt-unicode rofi neovim libwnck-3-0 libyajl2 libfreetype6 shotgun xclip fonts-terminus ueberzug tmux libwebkit2gtk-4.1-0 gcr aerc tmux x11-xserver-utils
	 git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
	 cd ~/dmenufm && \
	 make  -j4 && sudo make install && \
	 cd ~/ && \
	 git clone https://github.com/rvaiya/warpd.git && \ 
	 cd warpd/ && \
	 make -j4 && sudo make install && \
	 cd ~/ && \
	 rm -rf warpd/ && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
	 chmod +x emojimenu && \
	 sudo mkdir -p /usr/share/emojimenu && \
	 sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
	 sudo mv emojimenu /usr/local/bin/emojimenu && \
	 git clone https://github.com/darkhz/bluetuith && \
	 cd bluetuith && \ 
	 go build main.go -o bluetuith-bin && \
	 mv bluetuith-bin /usr/bin/bluetuith && \
	 cd ~/ && \ 
	 git clone https://github.com/kspi/dmenu-frecency && \
	 sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
	 cargo install hacksaw && \
	 curl -fsSL https://raw.githubusercontent.com/AlfredoSequeida/hints/main/install.sh | bash 
	 ;;

	"fedora")
	
	 sudo dnf groupinstall "Development Tools" && sudo dnf install -y libX11-devel libXft-devel libXinerama-devel xorg-x11-server-Xorg xorg-x11-xinit git gcc gobject-introspection-devel cairo-gobject-devel pkg-config python3-devel gtk4 pipx pasystray kernel-devel pam-devel libxcb-devel zig xorg-x11-xauth xorg-x11-server brightnessctl gtk-layer-shell grim pulsemixer lf xsel htop redshift rtorrent rxvt-unicode rofi neovim libwnck-devel yajl-devel freetype-devel shotgun xclip terminus-fonts ueberzug tmux webkit2gtk4.1-devel gcr aerc xsetroot && \
	 git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
	 cd ~/dmenufm && \
	 make -j4 && sudo make install && \
	 cd ~/ && \
	 git clone https://github.com/rvaiya/warpd.git && \
	 cd warpd/ && \
	 make -j4 && sudo make install && \
	 cd ~/ && \
	 rm -rf warpd/ && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
	 curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
	 chmod +x emojimenu && \
	 sudo mkdir -p /usr/share/emojimenu && \
	 sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
	 sudo mv emojimenu /usr/local/bin/emojimenu && \
	 git clone https://github.com/darkhz/bluetuith && \
	 cd bluetuith && \
	 go build main.go -o bluetuith-bin && \
	 sudo mv bluetuith-bin /usr/bin/bluetuith && \
	 cd ~/ && \
	 git clone https://github.com/kspi/dmenu-frecency && \
	 sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
	 cargo install hacksaw && \
	 curl -fsSL https://raw.githubusercontent.com/AlfredoSequeida/hints/main/install.sh | bash
	 ;;

#        "Alpine")
#            apk add build-base libx11-dev libxft-dev libxinerama-dev xorg-server xinit
#            ;;
#        "Slackware")
#            slackpkg install gcc make autoconf automake libX11 libXft libXinerama xorg-server xinit
#            ;;
#        "OpenBSD")
#            pkg_add gmake autoconf automake libX11 libXft libXinerama xorg-server xinit
#            ;;
#        "FreeBSD")
#            sudo pkg install gcc gmake autoconf automake libX11 libXft libXinerama xorg-server xorg-xinit
#            ;;
#        "Void")
#            sudo xbps-install -S base-devel libX11-devel libXft-devel libXinerama-devel xorg-server xorg-xinit
#            ;;
#        "NixOS")
#            nix-env -iA nixos.gcc nixos.gnumake nixos.autoconf nixos.automake nixos.libX11 nixos.libXft nixos.libXinerama nixos.xorg.xorgserver nixos.xorg.xinit
#            ;;
#        "OpenSUSE")
#            sudo zypper install -t pattern devel_basis && sudo zypper install libX11-devel libXft-devel libXinerama-devel xorg-x11-server xorg-x11-xinit
#            ;;
	"arch") 

         sudo pacman -S base-devel cairo libx11 libxft libxinerama git python pango pkgconf gobject-introspection lf xsel htop brightnessctl redshift rtorrent rxvt-unicode rofi nvim libwnck3 yajl freetype2 shotgun xorg-xclipboard terminus-font ueberzug tmux webkit2gtk-4.1 gcr tmux xorg-xsetroot --noconfirm
	 git clone https://aur.archlinux.org/yay.git
	 cd yay/ 
	 makepkg -si 
	 yay -S warpd-git dmenufm-git bluetuith-git nitrogen dmenu-frecency pulsemixer pasystray-git hacksaw-git shotgun --noconfirm 
	 curl -fsSL https://raw.githubusercontent.com/AlfredoSequeida/hints/main/install.sh | bash
         ;;

	"artix") 

         sudo pacman -S base-devel cairo libx11 libxft libxinerama git python pango pkgconf gobject-introspection lf xsel htop brightnessctl redshift rxvt-unicode rofi nvim libwnck3 yajl freetype2 terminus-font ueberzug tmux webkit2gtk-4.1 gcr tmux xorg-xsetroot  --noconfirm
        git clone https://aur.archlinux.org/yay.git
        cd yay/ 
        makepkg -si 	
        curl -fsSL https://raw.githubusercontent.com/AlfredoSequeida/hints/main/install.sh | bash
        ;;

        *)
            echo "Owo ?????????????? need a distro buddy!!!!!!11"
            exit 1
            ;;
    esac
}

case "$1" in

    -e)
     if [[ $# -gt 1 ]]; then
	$TRM -e $TXT "${@:2}" 
     else 
	$TXT "${@:2}"
     fi
        ;;

    -fm)

     if [[ $# -gt 1 ]]; then
	$FM "${@:2}" &
     else 
	$FM &
     fi
        ;;

    -c)
     if [[ $# -gt 1 ]]; then
	$IM "${@:2}" &
     else 
	$IM &
     fi
        ;;

    -t)
     if [[ $# -gt 1 ]]; then
	$TRM -e "${@:2}" &
     else 
	$TRM &
     fi
     ;;

    -m) 

     if [[ $# -gt 1 ]]; then
	$MU -e "${@:2}" &
     else 
	$MU &
     fi
        ;;
	
    -M) 

     if [[ $# -gt 1 ]]; then
	$IX -e "${@:2}" &
     else 
	$IX &
     fi
        ;;

    -K) 

     if [[ $# -ge 1 ]]; then
	if [[ -e "$KANATA" ]]; then
	kanata -c "$KANATA" "${@:3}" &
	fi
     else 
	echo "seem 2 b missing the kanata configuration. :3" &
	notify-send "seem 2 b missing the kanata configuration. :3" &
     fi
        ;;


    -g)
	FUNC=$(echo -e "clone\nfetch\npull\npush" | dmenu -i -f -fn $FONT -nb black -nf white -sb white -sf black -p "::git")
	case $FUNC in
		clone)
		URL=$(echo -e "" | dmenu -i -f -fn $FONT -nb black -nf white -sb white -sf black -p "::cl")
		notify-send "GIT: '$URL'"
		
		if [ -z "$URL" ]; then
		    notify-send "GIT: NONE"
		    exit 1
		fi
		
		REPO=""
		DIR=""
		
	
		if [[ "$URL" =~ ^https?://(github|gitea|codeberg|gitlab)\.com/(.*)/(.*)\.git$ ]]; then
		    REPO="${BASH_REMATCH[3]}"   
		    DIR="${BASH_REMATCH[2]}"    
		elif [[ "$URL" =~ ^([^/]+)/([^/]+)$ ]]; then
		    DIR="${BASH_REMATCH[1]}"    
		    REPO="${BASH_REMATCH[2]}"    
		    URL="https://github.com/${DIR}/${REPO}.git"  
		else
		    notify-send "GIT: [URL] OR [[NAME]/[REPO]]." & 
		    exit 1
		fi
		
		GITDIR="$(dmenufm -t -p)/$REPO"
		$TRM -cd $GITDIR -hold
	
		if [[ -d "$GITDIR" ]]; then
		    notify-send "GIT: [DIR_EXI]" &
		    exit 1
		fi
		
		# Attempt to clone the repository
		if git clone "$URL" "$GITDIR"; then
		    notify-send "GIT: $REPO [CLONED]" &
		else
		    notify-send "GIT: $REPO [CLFAIL]." & 
		    exit 1
		fi
		;;

	init)
		DIR=$(dmenufm -t -p)
		$TRM -cd $DIR -e git init 
		;;
	fetch)
		DIR="$(dmenufm -t -p)"
		$TRM -cd $DIR -e git fetch 
		;;

	pull)
		DIR="$(dmenufm -t -p)"
		$TRM -cd $DIR -e git pull
		;;

	push)
		DIR="$(dmenufm -t -p)"
		$TRM -cd $DIR -e git pull
		;;
       esac
       ;;

	-d)


	MONITOR=$(xrandr --query | grep " connected" | awk '{print $1}')
	PRIMARY=$(xrandr --query | grep " connected primary" | awk '{print $1}')
	
	SEL=$(echo "$MONITOR" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::disp")
	[ -z "$SEL" ] && exit 0
	
	ACTION=$(echo -e "direction\nref.rate\nscale" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::action")
	[ -z "$ACTION" ] && exit 0
	
	case "$ACTION" in
	    direction)
	        POSITION=$(echo -e "Left\nRight\nAbove\nBelow\nMirror\nOnly" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::pos")
	        [ -z "$POSITION" ] && exit 0
	        case "$POSITION" in
	            Left|Right|Above|Below) xrandr --output "$SEL" --auto "--${POSITION,,}-of" "$PRIMARY" ;;
	            Mirror) xrandr --output "$SEL" --auto --same-as "$PRIMARY" ;;
	            Only) xrandr --output "$SEL" --auto && for m in $MONITOR; do [ "$m" != "$SEL" ] && xrandr --output "$m" --off; done ;;
	        esac
	        ;;
	    "ref.rate")
	        RATES=$(xrandr --query | grep -A 100 "^$SEL connected" | grep -oP '\d+\.\d+(?=\*)?' | sort -u)
	        [ -z "$RATES" ] && exit 0
	        RATE=$(echo "$RATES" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::rate")
	        [ -z "$RATE" ] && exit 0
	        xrandr --output "$SEL" --rate "$RATE"
	        ;;
	    scale)
	        SCALE_OPTION=$(echo -e "custom\n0.5x\n0.75x\n1.0x (Normal)\n1.25x\n1.5x\n2.0x" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::scale")
	        [ -z "$SCALE_OPTION" ] && exit 0
	        
	        case "$SCALE_OPTION" in
	            "custom value")
	                CUSTOM=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::value")
	                [ -z "$CUSTOM" ] && exit 0
	                xrandr --output "$SEL" --scale "$CUSTOM"
	                ;;
	            *)
	                SCALE=$(echo "$SCALE_OPTION" | grep -oP '^\d+\.?\d*')
	                xrandr --output "$SEL" --scale "$SCALE"
	                ;;
	        esac
	        ;;
	esac
    ;;

    -b)

	mtnbrwse() {
	        mkdir -p $WEBDIR &
		mkdir -p $WEBD &
		QRY=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::url") 
	            if [[ ! -z $QRY ]]; then
	               	    OPT4WB="$(echo -e "url\nsrc" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::opt")"
			    case $OPT4WB in
				    src)
	                        	TOROPT=$(echo -e "tor\ncw" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::brw")
	                        	case $TOROPT in
						tor)
	                        	    	    torb "https://duckduckgo.com/?q=$(echo "$QRY" | tr ' ' '+')" &
						    echo $QRY >> $WEBHIST
						    ;;
						cw)
	                        	    	    $WEB "https://duckduckgo.com/?q=$(echo "$QRY" | tr ' ' '+')" &
						    echo $QRY >> $WEBHIST
						    ;;
					esac
				    ;;



			           url)
	                        	TOROPT=$(echo -e "tor\ncw" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::brw")
					case $TOROPT in
	                        	     tor) 
	                        	         torb "$QRY" &
						 echo $QRY >> $WEBHIST
					         ;;
				    	     cw)
	                        	         $WEB "$QRY" &
						 echo $QRY >> $WEBHIST
					         ;;
				 	esac
					;;
			   esac
		    fi
		}

	
	OPT="$(echo -e "web\ngit\nim\nem" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::opt")"
	case "$OPT" in
	    "web")
		OPTW="$(echo -e "+\nhist\nbkm\nck" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::opt")"
		case "$OPTW" in 
			hist)
			    OPTHIST="$(echo -e "$(awk '{ printf "%s\\n",$1 }' $WEBHIST)" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p ::hist)"
	            	    if [[ ! -z $OPTHIST ]]; then
				    $WEB $OPTHIST
			    else
				    exit
			    fi
			    ;;
			"+")
			    mtnbrwse
			    ;;
	       		esac

			;;
	    "im")
	        wm -c
	        ;;
	    "git")
	        wm -g
	        ;;
	    "em")
	        EM=$(echo -e "snd\nrcv" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::em")
	        case "$EM" in
	            snd)
	                SEND=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "->")
	                $IX mailto:"$SEND"
	                ;;
	            rcv)
	                RECV=$(echo -e "acc\nmx" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "<-")
	                case "$RECV" in
	                    acc)
	                        ACC=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::acc")
	                        $IX -a $ACC
	                        ;;
	                    mx)
	                        MX=$(dmenufm -t -p)
	                        $IX -e mbox:"$MX"
	                        ;;
	                esac
	                ;;
	        esac
	        ;;
	esac
	    ;;

    -w)
	# will later be replaced by a feh-based wallpaper setting function.
	nitrogen --restore & 
        ;;

    -se)
	FILE="$HOME/.config/nhk/.urlquery"
	
	if [ ! -f $FILE ]; then
	    touch $FILE
	fi
	
	FILEOPT=$(cat $FILE)
	
	OPTIONS="
	[
	${FILEOPT}
	[ \"+\", \"\" ],
	[ \"-\",  \"\" ]
	]
	"
	
	OBJ_LENGTH=$(echo $OPTIONS | jq length)
	OBJ_MENU=$(echo $OPTIONS | jq -r ".[][0]" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::src")
	OBJ_QRY=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::query")
	OBJ_KEYWORDS=$(echo "$OBJ_QRY" | tr " " "+")
	OBJ_SELECTED=$(echo "$OBJ_MENU" | cut -d' ' -f1)
	
	wikihntr() {
	    for i in $(seq 0 $((OBJ_LENGTH - 1))); do
	        if [ "$OBJ_SELECTED" = "+" ]; then
	            PREFIXMENU=$(echo "" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::prfx[a]" <&-)
	            URLQUERY=$(echo "" | dmenu -fn $FONT -nb black -nf white -sb white -sf black -p "::url[b]" <&-)
	            if [ ! -z "$PREFIXMENU" ]; then
	                echo "[ \"$PREFIXMENU\", \"$URLQUERY\" ]," >> $FILE
	            fi
	
	        elif [ "$OBJ_SELECTED" = "-" ]; then
	            OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | head -n -2 | dmenu -fn $FONT -nb black -nf white -sb white -sf black -i -p "::del")
	            sed -i "/$OBJ_MENU/d" $FILE
	        fi
	        
	        if [ "$OBJ_SELECTED" = "$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][0]')" ]; then
	            URLQUERY=$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][1]')
	            KEYWORDS=$(echo "$OBJ_KEYWORDS")
	            xdg-open "${URLQUERY}${KEYWORDS}" 2> /dev/null
	        fi
	    done
	}
	
	wikihntr
	;;

    -sf)
	
        shotgun - | xclip -selection clipboard -t image/png
        filename=${filename:-$(date +%s)} && \
        mkdir -p $NHK/s/
        shotgun $NHK/s/"$filename.png"
        ;;

    -ss)

        selection=$(hacksaw -f "-i %i -g %g")
        shotgun $selection - | xclip -selection clipboard -t image/png
        filename=${filename:-$(date +%s)} && \
        mkdir -p $NHK/s/
        shotgun $selection $NHK/s/"$filename.png"
        ;;


   -sv)

    	dir=$NHK/widow/s/video/
    	current=$(date +%F_%H-%M-%S)
    	
    	mkdir -p "$dir"
    	hacksaw | {
    	    IFS=+x read -r w h x y
    	
    	    w=$((w + w % 2))
    	    h=$((h + h % 2))
    	
    	    $TRM -e ffmpeg \
    	        -v 16            \
    	        -r 30            \
    	        -f x11grab       \
                -s "${w}x${h}"   \
    	        -i ":0.0+$x,$y"  \
    	        -preset slow     \
    	        -c:v libx264        \
    	        -pix_fmt yuv420p \
    	        -crf 20          \
    	        -f pulse -i default \
    	        "$dir/$current.mp4" & \
		
    		}
	;;

   -ar)

   	   directory=$NHK/ar/
   	   date=$(date +%F_%H-%M-%S)
	   mkdir -p $directory
           $TRM -e ffmpeg -f pulse -i default "$directory/$date".wav

    	;;

   -T) 
	   wm -t $TXT $NHK/src/.nhktutorial & 
	   ;; 
   
   -pk) 
         sudo cp -rv $HOME/.local/bin/wm $NHK/yr/
         sudo cp -rv $HOME/.local/bin/lb $NHK/yr/
	 cp -rv ~/.config/sxhkd/* $NHK/xk/
	 cp -rv ~/.config/warpd/config $NHKCFG/warpd.config
	 cp -rv ~/.config/hints/config.json $NHKCFG/config.hints.json
	 cp -rv ~/.config/dunst/dunstrc $NHKCFG/
	 cp -rv ~/.config/polybar/config.ini $NHKCFG/polybar.config.ini
	 cp -rv ~/.local/bin/foxtag $NHKCFG/
	 cp -rv ~/.config/dmenu-frecency/config.json $NHKCFG/dmenu-frecency.config.json
	 cp -rv ~/.config/polybar/config.ini $NHKCFG/polybar.config.ini 
	 cp -rv ~/.Xresources_nhk $NHKCFG/
	 cp -rv ~/.config/lf/lfrc $NHKCFG/
	 cp -rv ~/.config/mimi/mime.conf $NHKCFG/
	 cp -rv ~/.nhktx.conf $NHKCFG/
	 cp -rv ~/.local/bin/lfp $NHKCFG/
	 cp -rv ~/.local/bin/foxtag $NHK/xt/
	 cp -rv ~/.local/bin/wiconv $NHK/xt/
	 cp -rv ~/.local/bin/slmenu $NHK/xt/
	 cp -rv ~/.config/hints/config.json $NHKCFG/config.hints.json 
	 ;;

  -upk)  
	 wideps $2
	
   	 cd $NHK/src/xtr
	 cd $NHK/src/xtr/dmenu/ && make -j$CORE && sudo make install
	 cd $NHK/src/xtr/lock/ && make -j4$CORE && sudo make install
	 cd $NHK/src/xtr/nsxiv/ && make -j$CORE && sudo make install
	 cd $NHK/src/xtr/dunst/ && make -j$CORE && sudo make install
	 cd $NHK/src/xtr/sxhkd/ && make -j$CORE && make clean && make && sudo make install
	 cd $NHK/src/xtr/dwmblocks/ && make -j$CORE && sudo make install
	 cd $NHK/src/xtr/surf/ && make -j$CORE  && sudo make install
	 cd $NHK/src/xtr/surf/wyebadblock/ && make -j$CORE && sudo make install
	 sudo mkdir /usr/local/lib/surf && sudo ln -s /usr/lib/wyebrowser/adblock.so /usr/local/lib/surf
	 cd $NHK
	 mkdir -p $HOME/.config/nhk
	 cp -rv $NHK/yr/lb $HOME/.local/bin/
	 cp -rv $NHK/yr/wm $HOME/.local//bin 
	 cp -rv $NHK/yr/omni $HOME/.local//bin 
	 chmod +x /usr/bin/wm 
	 chmod +x /usr/bin/lb 
	 chmod +x /usr/bin/omni
	 mkdir -p ~/.config/polybar/
	 mkdir -p ~/.config/dmenu-frecency/ 
	 cp -rv $NHKCFG/dmenu-frecency.config.json ~/.config/dmenu-frecency/config.json
	 mkdir -p ~/.config/dunst/
	 cp -rv $NHKCFG/dunstrc ~/.config/dunst/
	 mkdir -p ~/.config/hints/
	 cp -rv $NHKCFG/config.hints.json ~/.config/hints/config.json
	 mkdir -p ~/.config/warpd/
	 cp -rv $NHKCFG/warpd.config ~/.config/warpd/config 
	 mkdir -p ~/.config/sxhkd && cp -rv $NHK/xk/* ~/.config/sxhkd/
	 cd $NHK
	 mkdir -p ~/.config/mimi 
	 cp -rv $NHKCFG/mimi.conf ~/.config/mimi/mime.conf
	 mkdir -p ~/.local/bin 
	 cp -rv xt/foxtag ~/.local/bin/
	 cp -rv xt/wiconv ~/.local/bin/
         cp -rv xt/slmenu ~/.local/bin/
	 cp -rv $NHKCFG/.Xresources_nhk $HOME/
	 xrdb -merge ~/.Xresources_nhk
	 git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	 cp -rv $NHKCFG/.nhktx.conf ~/
	 tmux source-file ~/.nhktx.conf
	 cd $NHK/src
         sudo make clean install
	 sudo mkdir -p /usr/share/xsessions/ 
	 sudo cp -rv $NHK/src/nhk.desktop /usr/share/xsessions/
	 sudo chmod +x patch/dwmc
	 sudo cp -rv patch/dwmc /usr/bin/dwmc
	 cd $NHK
         ;;

   -q)
         QRY=$(echo -e "w\nwq\nq" | dmenu -i -fn $FONT -nb black -nf white -sb white -sf black -p "::")
	 case $QRY in
		 "w")
		    $TRM -hold -cd $NHK/src -e sh -c "sudo make clean install && sudo mkdir -p /usr/share/xsessions/ && sudo cp -rv nhk.desktop /usr/share/xsessions/"
		    ;;

		  "wq")
		    $TRM -hold -cd $NHK/src -e sh -c "sudo make clean install && sudo mkdir -p /usr/share/xsessions/ && sudo cp -rv nhk.desktop /usr/share/xsessions/"
		    sleep 1
		    dwmc quit
		    ;;

	          "q")
		    dwmc quit 
		    ;;
	 esac
	 ;;

   -EE)

     if [[ $# -gt 1 ]]; then
	$TXT "${@:2}" 
     else 
	$TXT $NHK/yr/wm && sudo cp -rv $NHK/yr/wm .local/bin/wm
     fi

     ;;

    *)
	echo "
	wm 0.1 - nhk window management and configuration tool.
	EE: edit wm directly.
	pk/upk: (re)package/unpackage nhk-related configurations.	
	q: rebuild or simply quit dwm. 
	T: view nhk documentation.
	------------------------------
	ss: screenshotting function.
	sv: screen recording function.
	ar: audio recording function.
	------------------------------
	b: nhk metabrowser (metanet).
	c: open instant messenger.
	M: interact with email client.
	g: git management tool.
	d: display management tool.
	w: wallpaper setter (0.1 - nitrogen --restore).
	K: kanata management tool (0.1 - initializes kanata daemon).
	"
	;;
	
esac 
